name: eyed3

on:
  push:
    branches:
      - master
    paths:
      - 'eyed3/**'

env:
  IMAGE_NAME: eyed3
  IMAGE_PLATFORMS: linux/amd64,linux/arm64

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./${{ env.IMAGE_NAME }}
          push: true
          platforms: ${{ env.IMAGE_PLATFORMS }}
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest